### ISSUE TITLE
fix: stella says that dafny is a problem

### ISSUE THREAD

**Issue by andreedd** [Datateknologerna-vid-Abo-Akademi/date-website#195] opened 2021-12-03 22:44 UTC
**Is your fix request related to a problem?**  
When KK are uploading photos, their photos are so big that the memory runs out on the server

**Describe the solution you'd like**  
More memory on server?
Different way of uploading images

**Additional context**  
Django Daphne, not dafny

**Comment by andreedd** [comment] 2021-12-03 22:46
Sofia agrees that dafny is a problem

**Comment by JoarSabel** [comment] 2023-03-16 18:10
?

**Comment by jaspnas** [comment] 2023-06-30 22:12
Duplicate of #186

**Closed as completed by jaspnas** 2023-06-30 22:12 UTC
Labels: feature
