### ISSUE TITLE
bug: Unable to delete event attendee after moving it in the attendee list

### ISSUE THREAD

**Issue by andreedd** [Datateknologerna-vid-Abo-Akademi/date-website#238] opened 2022-03-03 08:34 UTC
**Describe the bug**  
Joar:
tror dock ja hitta en bug 😆man verkar int kuna klick i deletebox på en person efter att man ha flytta folk'

Can't move a person in events admin and then delete

**To Reproduce**  
move attendee and try to delete 

**Sidenote:**
You are able to delete after saving the form

**Comment by WilliamNylund** [comment] 2022-03-30 15:56
Could not reproduce. @JoarSabel plz show.

**Comment by jaspnas** [comment] 2023-06-30 23:57
Probaly not a problem as this doesn't break anything. Closing as wontfix for now

**Closed as not planned by jaspnas** 2023-06-30 23:57 UTC
Labels: bug

**Comment by nDny** [comment] 2023-07-03 08:24
Maybe better to close it like this and not complete.
